from accounts.views.registration_view import RegistrationView
from accounts.views.username_change_view import UsernameChangeView
from accounts.views.users_list_view import UsersListView
from accounts.views.user_detailed_view import UserDetailedView
