from articles.views.categories.add_category_view import AddCategoryView
from articles.views.categories.categories_list_view import CategoriesListView
from articles.views.categories.update_category_view import UpdateCategoryView
from articles.views.categories.delete_category_view import DeleteCategoryView
